[colors]
    draw_bold_text_with_bright_colors = true

    [colors.bright]
        black   = "#625e4c"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#f6f6ef"
        yellow  = "#e0d561"

    [colors.normal]
        black   = "#1a1a1a"
        blue    = "#9d65ff"
        cyan    = "#58d1eb"
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#c4c5b5"
        yellow  = "#fa8419"

    [colors.primary]
        background = "0x1a1b26"
        foreground = "0xa9b1d6"

[font]
	size = 11.0

[font.bold]
        family = "FiraCode"
        style  = "Bold"

[font.bold_italic]
        family = "FiraCode"
        style  = "Bold Italic"

[font.glyph_offset]
        x = 0
        y = 0

[font.italic]
        family = "FiraCode"
        style  = "Italic"

[font.normal]
        family = "FiraCode"
        style  = "Regular"

[font.offset]
        x = 0
        y = 0

[window.padding]
	x = 15
	y = 15

[window]
	decorations = "Transparent"
	dynamic_title = true
	blur = false
	opacity = 0.85
